

;deploy-programs searches for an optional file named .deployProgramsMetadata.ini 
;starting with the current working directory ($PWD) up to the user root ($HOME)
;It is normal to place this file at $HOME/.deployPrograms.ini 
;The [aliases] section gives short names for paths to simplify use in a situation 
;where many programs and servers are being managed.
;The path being referenced is a normal, program/server specific config file.
;The alias is placed (no dollar sign) where a fileName would appear. 
;If the string is found in the config file, that corresponding path is used to
;locate the config. If it not found in the [aliases] list, it is treated 
;as a path and used if a proper config is found there.

[aliases]

demo=/PATH/TO/deployPrograms.ini